apiVersion: /v1
kind: Service
metadata:
  name: memphis-ui
  namespace: memphis
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: memphis-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-ui
  namespace: memphis
  labels:
    app: memphis-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-ui
  template:
    metadata:
      name: memphis-ui
      labels:
        app: memphis-ui
    spec:
      containers:
        - name: memphis-ui
          image: 221323242847.dkr.ecr.eu-central-1.amazonaws.com/memphis-ui-staging:latest
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "staging"
